apiVersion: v1
kind: Pod
metadata:
  name: kaniko-demo
spec:
  containers:
  - name: kaniko
    image: tannuahuja14/kaniko-demo:latest  # Use your locally built image name
    args:
    - "--context=git://github.com/tannuahuja14/kaniko-kubernetes.git"
    - "--dockerfile=Dockerfile"
    - "--destination=docker.io/tannuahuja14/kaniko-demo:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
